serveur:
  port: 8081

printemps:
  application:
    nom: SERVICE-CLIENT
  source-de-donnees:
    pilote-class-nom: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://serveur-local:3306/bd_service_clients?creerBaseSiNonExistante=vrai
    nom-utilisateur: "administrateur"
    mot-de-passe: "admin1234"
  jpa:
    hibernate:
      ddl-auto: creer
      afficher-sql: vrai

eureka:
  client:
    url-service:
      zone-par-defaut: http://serveur-local:8761/eureka/
  instance:
    preferer-adresse-ip: vrai